server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Twitter
          jwk-set-uri: http://localhost:8180/realms/Twitter/protocol/openid-connect/certs
  datasource:
    url: ${DB_URL}
    username: admin
    password: 123698745
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: ${DB_URL}
    locations: filesystem:${PROJECT_HOME}/twitter/db/migrations
    user: admin
    password: 123698745
    schemas: twitter
  session:
    jdbc:
      initialize-schema: always