server:
  port: 8080

spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8180/realms/Twitter
#          jwk-set-uri: http://localhost:8180/realms/Twitter/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/twitter
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://${DB_HOST}:3306/twitter
    locations: filesystem:${PROJECT_HOME}/db/migrations
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    schemas: twitter
  session:
    jdbc:
      initialize-schema: always